### PR TITLE
add photoLocalurl() and savephoto() methods in Name class

### PR DESCRIPTION
**Pull request by jcvignoli**
Issue https://github.com/duck7000/imdbGraphQLPHP/issues/126

### CODE REVIEW

**Comment by duck7000** [comment]
1. Mistake in doc bloc line 203 (need to be Name instead of movies
2. mistake in doc bloc line 207 (need to be NamePage)

**Comment by jcvignoli** [comment]
Fixed. Same for savephoto() method.

**Comment by duck7000** [comment]
To be a real picky reviewer

Line 304 names should be Name ;)

**Comment by jcvignoli** [comment]
> To be a real picky reviewer
> 
> Line 304 names should be Name ;)

I didn't understand it like a word refering to the class! Fixed.

**Comment by duck7000** [comment]
Great, i approve your PR

**Comment by jcvignoli** [comment]
you just approved my first PR ever ;)

**Comment by duck7000** [comment]
congrates, my first one was for imdbphp, it took ages and a hard bargain to finally get something approved..
So i don't want to be like that.

**Pull request merged**
